### ISSUE TITLE
How can i found label?

### ISSUE THREAD

**Issue by jerry-hansol** [SomTambe/ModelNet10-dataset#1]
For example, arr[76] is chair but how can i know it before render?

**Comment by SomTambe** [comment]
I think it will be in the order of how binvox files have been arranged. Make sure you check your binvox files to get an idea of how your classes have been arranged; like if first 300 are chair then arr[299] will be the last index of chair.

**Comment by SomTambe** [comment]
I am closing this issue. Kindly reopen it anytime if you have a problem or a doubt.
